from typing import Any

ZOHO_TICKET_WEBHOOK_EXAMPLE: dict[str, Any] = {
    "modifiedTime": "2026-04-15T19:17:54.000Z",
    "subCategory": None,
    "statusType": "Open",
    "subject": "test adk - C-DIGITAL",
    "dueDate": "2026-04-20T19:17:17.000Z",
    "departmentId": "474709000000006907",
    "channel": "Web",
    "onholdTime": None,
    "language": None,
    "source": {
        "appName": None,
        "extId": None,
        "permalink": None,
        "type": "SYSTEM",
        "uuid": None,
        "appPhotoURL": None,
    },
    "resolution": None,
    "sharedDepartments": [],
    "closedTime": None,
    "approvalCount": "0",
    "isOverDue": False,
    "isTrashed": False,
    "createdTime": "2026-04-15T19:17:17.000Z",
    "id": "474709001374378051",
    "isResponseOverdue": False,
    "customerResponseTime": "2026-04-15T19:17:17.000Z",
    "productId": None,
    "contactId": "474709000810637250",
    "threadCount": "1",
    "secondaryContacts": [],
    "priority": None,
    "classification": None,
    "commentCount": "0",
    "taskCount": "0",
    "accountId": None,
    "phone": "3204218988",
    "webUrl": "https://desk.zoho.com/support/servicioscun/ShowHomePage.do#Cases/dv/474709001374378051",
    "isSpam": False,
    "status": "Open",
    "entitySkills": [],
    "ticketNumber": "3510366",
    "sentiment": None,
    "customFields": {
        "FECHA ESCALAMIENTO PROGRAMACIÓN ACADÉMICA": None,
        "Enviar correo": None,
        "¿Qué deseas responder con tu requerimiento?": None,
        "Observación compras": None,
        "Ticket formulario?": None,
        "¿Qué tema aborda tu requerimiento?": None,
        "Fecha-Escalado por": None,
        "Brief": None,
        "Concepto de la disponibilidad": None,
        "Lista de selección 1": None,
        "ODC": None,
        "Fuerza": None,
        "SUB CATEGORIA II": "N/A",
        "¿CUÁL ES TU VICERRECTORIA O DIRECCIÓN?": None,
        "REGIONAL - SEDE.": None,
        "Tipo solicitante": None,
        "Docente asignado": None,
        "Correo electrónico 1": None,
        "educacioncontinuada@corporaciontelecampus.zohodesk": None,
        "Fecha - escalado por": None,
        "Solicitud Ticket": None,
        "Nivel": None,
        "Tipo de categoría": None,
        "MOTIVO PYB": None,
        "Periodo a Ingresar": None,
        "Fecha Escalado": None,
        "FORMATO DE NECESIDADES": None,
        "Fecha cambio propietario": "2026-04-15T19:17:54.000Z",
        "Valor total": None,
        "FECHA ESCALAMIENTO REGISTRO Y CONTROL": None,
        "Escalamiento LMS": None,
        "CERRADO POR-AA": None,
        "REGIONAL - SEDE": "REGIONAL BOGOTA",
        "Associated Type": None,
        "¿Solicita Financiera?": None,
        "¿En qué tema te podemos ayudar?": None,
        "Nombre del proveedor": None,
        "COMPONENTE": None,
        "Escalamiento Escuela de Idiomas": None,
        "Numero Ticket": "3510366",
        "Observación Documental Gv": None,
        "Observaciones": " - No se encontró una oportunidad asociada. - No se encontró una oportunidad asociada.",
        "MES": None,
        "Documento": None,
        "MANEJA ODC": None,
        "Parent Ticket ID": None,
        "Ticket cierre masivo": "false",
        "ID SOLICITUD CREATOR": None,
        "Observación Académica Gv": None,
        "Cierre Grados": None,
        "Valor total Iva Incluido Compras": None,
        "CONSECUTIVO DE SOLICITUD": None,
        "Observaciones académico ": None,
        "MOTIVO.": None,
        "Tipo de solicsitante": None,
        "Escalamiento Back": None,
        "Cantidad de unidades de medida a solicitar": None,
        "OTRO METODO DE PAGO": None,
        "Programa": "INGENIERÍA DE SISTEMAS",
        "Judicante asesor": None,
        "SUB ESTADO TICKET": None,
        "Modalidad": "Virtual",
        "Fecha-Escalamiento LMS": None,
        "Tipo de categoría tex": None,
        "Programa del que proviene": None,
        "SUB CATEGORIAS": "C-DIGITAL",
        "Observación Servicio Grados": None,
        "Número de documento": "1032416218",
        "Escalamiento Academia": None,
        "Escalado por": None,
        "ESCALAMIENTO CERTIFICADOS": None,
        "Programa.": None,
        "¿Escalado?": None,
        "ESCALMIENTO REGISTRO Y CONTROL": None,
        "Colaborador asignado": None,
        "ESCALAMIENTO PROGRAMACIÓN ACADÉMICA": None,
        "PROGRAMA A HOMOLOGAR": None,
        "Institucion de la que proviene": None,
        "Escalamiento Contact": None,
        "Numero Masivo": None,
        "Periodo": "26V02",
        "SOLICITUD": "TECNOLOGÍA",
        "METODO DE PAGO": None,
        "ES MULTI": None,
        "Equipo": None,
        "Codigo SNIES": None,
        "Ultimo agente": None,
        "Área": None,
        "MOTIVO": None,
        "PROYECTO": None,
        "NIT": None,
        "Escalado PyB": None,
        "FECHA ESCALAMIENTO CERTIFICADOS": None,
        "CATEGORIA": "FALLA EN PLATAFORMAS O REESTABLECIMIENTO DE USUARIOS DIGITALES",
        "NUMERO DE RADICADO": None,
    },
    "isArchived": False,
    "description": "<div>test adk</div>",
    "timeEntryCount": "1",
    "channelRelatedInfo": None,
    "responseDueDate": None,
    "isDeleted": False,
    "modifiedBy": "474709000000130025",
    "followerCount": "0",
    "email": "jhonatan_delgado@cun.edu.co",
    "layoutDetails": {
        "id": "474709000000074011",
        "layoutName": "Cami Tikets",
    },
    "channelCode": None,
    "isFollowing": False,
    "cf": {
        "cf_fecha_escalado_por_1": None,
        "cf_solicitud_ticket": None,
        "cf_ticket_cierre_masivo": "false",
        "cf_proyecto": None,
        "cf_nit": None,
        "cf_tipo_de_solicsitante": None,
        "cf_observacion_financiera": None,
        "cf_regional": "REGIONAL BOGOTA",
        "cf_documento": None,
        "cf_educacioncontinuada_corporaciontelecampus_zohodesk": None,
        "cf_lista_de_seleccion_1_1": None,
        "cf_maneja_odc": None,
        "cf_regional_sede": None,
        "cf_nivel": None,
        "cf_programa_del_que_proviene": None,
        "cf_escalado_por": None,
        "cf_area": None,
        "cf_brief": None,
        "cf_fecha_escalamiento_lms": None,
        "cf_escalamiento_academia": None,
        "cf_periodo_a_ingresar": None,
        "cf_motivo": None,
        "cf_motivo_1": None,
        "cf_de_que_tema_se_trata_tu_requerimiento": None,
        "cf_solictud": "TECNOLOGÍA",
        "cf_escalamiento_programacion_academica": None,
        "cf_associated_type": None,
        "cf_que_deseas_responder_con_tu_requerimiento": None,
        "cf_escalmiento_registro_y_control": None,
        "cf_escalamiento_contact": None,
        "cf_observacion_documental_gv": None,
        "cf_ticket_formulario": None,
        "cf_observacion_compras": None,
        "cf_concepto_de_la_disponibilidad": None,
        "cf_escalamiento_escuela_de_idiomas": None,
        "cf_enviar_correo": None,
        "cf_linea_unica_1": None,
        "cf_periodo": "26V02",
        "cf_fecha_escalamiento_registro_y_control": None,
        "cf_fecha_escalado_por": None,
        "cf_numero_de_radicado": None,
        "cf_otro_metodo_de_pago": None,
        "cf_se_debe_tramitar": None,
        "cf_judicante_asesor": None,
        "cf_metodo_de_pago": None,
        "cf_lista_de_seleccion_1": None,
        "cf_sub_categorias": "C-DIGITAL",
        "cf_cierre_grados": None,
        "cf_modalidad": "Virtual",
        "cf_categoria": "FALLA EN PLATAFORMAS O REESTABLECIMIENTO DE USUARIOS DIGITALES",
        "cf_programa_a_homologar": None,
        "cf_componente": None,
        "cf_institucion_de_la_que_proviene": None,
        "cf_parent_ticket_id": None,
        "cf_mes": None,
        "cf_solicita_financiera": None,
        "cf_sub_categoria_ii": "N/A",
        "cf_escalado_pyb": None,
        "cf_cerrado_por_aa": None,
        "cf_observaciones_academico": None,
        "cf_numero_de_documento": "1032416218",
        "cf_escalamiento_certificados": None,
        "cf_correo_electronico_1": None,
        "cf_escalamiento_back": None,
        "cf_nombre_del_proveedor": None,
        "cf_colaborador_asignado": None,
        "cf_codigo_snies": None,
        "cf_cantidad_de_unidades_de_medida_a_solicitar": None,
        "cf_programa": "INGENIERÍA DE SISTEMAS",
        "cf_ultimo_agente": None,
        "cf_numero_masivo": None,
        "cf_numero_ticket": "3510366",
        "cf_sub_estado_ticket": None,
        "cf_en_que_tema_te_podemos_ayudar": None,
        "cf_programa_1": None,
        "cf_es_multi": None,
        "cf_odc": None,
        "cf_valor_total_iva_incluido_compras": None,
        "cf_motivo_a": None,
        "cf_fecha_cambio_propietario": "2026-04-15T19:17:54.000Z",
        "cf_observacion_academica_gv": None,
        "cf_fuerza": None,
        "cf_valor_total": None,
        "cf_escalamiento_lms": None,
        "cf_fecha_escalado": None,
        "cf_docente_asignado": None,
        "cf_tipo_de_categoria_tex": None,
        "cf_observaciones": " - No se encontró una oportunidad asociada. - No se encontró una oportunidad asociada.",
        "cf_tipo_solicitante": None,
        "cf_fecha_escalamiento_certificados": None,
        "cf_id_solicitud_creator": None,
        "cf_equipo": None,
        "cf_tipo_de_categoria_multicartoria_categoria_sencil": None,
        "cf_escalado": None,
        "cf_fecha_escalamiento_programacion_academica": None,
    },
    "slaId": "474709000006380458",
    "layoutId": "474709000000074011",
    "assigneeId": "474709001373955408",
    "createdBy": "474709000810637276",
    "teamId": None,
    "tagCount": "0",
    "attachmentCount": "0",
    "isEscalated": False,
    "category": None,
}

ZOHO_TICKET_WEBHOOK_OPENAPI_EXAMPLES: dict[str, Any] = {
    "zoho_ticket_completo": {
        "summary": "Payload completo de Zoho Desk",
        "description": "Ejemplo real de ticket con customFields y cf para validacion funcional.",
        "value": ZOHO_TICKET_WEBHOOK_EXAMPLE,
    }
}

ZOHO_TICKET_WEBHOOK_ACCEPTED_RESPONSE_EXAMPLE: dict[str, str] = {
    "status": "accepted",
    "appName": "helpdesk_agent",
    "userId": "user_474709000810637250",
    "sessionId": "ticket_474709001374378051",
    "ticketId": "474709001374378051",
}
